
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kanav
 */
public class TicTacToe extends javax.swing.JFrame {
 static int player1=0;
 static int player2=0;
 
    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
        jLabel1.setText(new Start().P1);
        jLabel2.setText(new Start().P2);
        jButton2.setText(new Start().P1);
        jButton3.setText(new Start().P2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Player 1");

        jLabel2.setText("Player 2");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);

        jTextField4.setEditable(false);

        jTextField5.setEditable(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setEditable(false);

        jTextField7.setEditable(false);

        jTextField8.setEditable(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setEditable(false);

        jTextField10.setEditable(false);

        jTextField11.setEditable(false);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jButton2.setText("Player 1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Player 2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Re-Play");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Scoreboard");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField7)
                                            .addComponent(jTextField4)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(125, 125, 125)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(187, 187, 187)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3))
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                        .addComponent(jTextField13))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(78, 78, 78)
                                .addComponent(jButton5)))))
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //text field editable
        
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        
        // submit button lock
        jButton1.setEnabled(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            //Player1
        if(jTextField12.getText().equals("1"))
        {
            if(jTextField3.getText().isEmpty())
            {
                 jTextField3.setText( jTextField1.getText());
            }    
           
       
        }
          else if(jTextField12.getText().equals("2"))
        {
             if(jTextField4.getText().isEmpty())
             { 
                 jTextField4.setText( jTextField1.getText());
             }
       
        }
         else if(jTextField12.getText().equals("3"))
        {
             if(jTextField5.getText().isEmpty())
             {
                 jTextField5.setText( jTextField1.getText());
             }
       
        }
         else if(jTextField12.getText().equals("4"))
        {
             if(jTextField6.getText().isEmpty())
             {
                 jTextField6.setText( jTextField1.getText());
             }
       
        }
         else if(jTextField12.getText().equals("5"))
        {
          if(jTextField7.getText().isEmpty())
          {
              jTextField7.setText( jTextField1.getText());
          }
       
        }
         else if(jTextField12.getText().equals("6"))
        {
            if(jTextField8.getText().isEmpty())
            {
                jTextField8.setText( jTextField1.getText());
            }
       
        }
         else if(jTextField12.getText().equals("7"))
        {
             if(jTextField9.getText().isEmpty())
             {
                 jTextField9.setText( jTextField1.getText());
             }
       
        }
         else if(jTextField12.getText().equals("8"))
        {
             if(jTextField10.getText().isEmpty())
             {
                 jTextField10.setText( jTextField1.getText());
             }
       
        }
         else if(jTextField12.getText().equals("9"))
        {
            if(jTextField11.getText().isEmpty())
            {
                jTextField11.setText( jTextField1.getText());
            }
       
        }
        
        
        //buttonchange
        
        jButton2.setEnabled(false);
        jButton3.setEnabled(true);
        
        
        // clear text of 1st text field
        jTextField12.setText("");
        
        
        //Winner
        
        //Variable declare
        String a= jTextField3.getText();
        String b= jTextField4.getText();
        String c= jTextField5.getText();
        String d= jTextField6.getText();
        String e= jTextField7.getText();
        String f= jTextField8.getText();
        String g= jTextField9.getText();
        String h= jTextField10.getText();
        String i= jTextField11.getText();
        
        
        //winner if commands
        if(a.equals(jTextField1.getText())&& e.equals(jTextField1.getText()) && i.equals(jTextField1.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 1 is the winner");
            player1=player1+1;   
        }
        else if(a.equals(jTextField1.getText())&& b.equals(jTextField1.getText()) && c.equals(jTextField1.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 1 is the winner");
        player1=player1+1;  
        }
        else if(a.equals(jTextField1.getText())&& d.equals(jTextField1.getText()) && g.equals(jTextField1.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 1 is the winner");
           player1=player1+1;  
           
            
        }
        else if(g.equals(jTextField1.getText())&& h.equals(jTextField1.getText()) && i.equals(jTextField1.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 1 is the winner");
           
           player1=player1+1;  
            
        }
        else if(c.equals(jTextField1.getText())&& f.equals(jTextField1.getText()) && i.equals(jTextField1.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 1 is the winner");
           
           player1=player1+1;  
            
        }
        else if(c.equals(jTextField1.getText())&& e.equals(jTextField1.getText()) && g.equals(jTextField1.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 1 is the winner");
           
           player1=player1+1;  
            
        }
        else if(b.equals(jTextField1.getText())&& e.equals(jTextField1.getText()) && h.equals(jTextField1.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 1 is the winner");
           player1=player1+1;  
           
            
        }
          else if(d.equals(jTextField1.getText())&& e.equals(jTextField1.getText()) && f.equals(jTextField1.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 1 is the winner");
           
           player1=player1+1;  
            
        }
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Player2
        if(jTextField13.getText().equals("1"))
        {
            if(jTextField3.getText().isEmpty())
            {
                 jTextField3.setText( jTextField2.getText());
            }    
           
       
        }
          else if(jTextField13.getText().equals("2"))
        {
             if(jTextField4.getText().isEmpty())
             { 
                 jTextField4.setText( jTextField2.getText());
             }
       
        }
         else if(jTextField13.getText().equals("3"))
        {
             if(jTextField5.getText().isEmpty())
             {
                 jTextField5.setText( jTextField2.getText());
             }
       
        }
         else if(jTextField13.getText().equals("4"))
        {
             if(jTextField6.getText().isEmpty())
             {
                 jTextField6.setText( jTextField2.getText());
             }
       
        }
         else if(jTextField13.getText().equals("5"))
        {
          if(jTextField7.getText().isEmpty())
          {
              jTextField7.setText( jTextField2.getText());
          }
       
        }
         else if(jTextField13.getText().equals("6"))
        {
            if(jTextField8.getText().isEmpty())
            {
                jTextField8.setText( jTextField2.getText());
            }
       
        }
         else if(jTextField13.getText().equals("7"))
        {
             if(jTextField9.getText().isEmpty())
             {
                 jTextField9.setText( jTextField2.getText());
             }
       
        }
         else if(jTextField13.getText().equals("8"))
        {
             if(jTextField10.getText().isEmpty())
             {
                 jTextField10.setText( jTextField2.getText());
             }
       
        }
         else if(jTextField13.getText().equals("9"))
        {
            if(jTextField11.getText().isEmpty())
            {
                jTextField11.setText( jTextField2.getText());
            }
       
        }
        
        
       //button change
        
        jButton2.setEnabled(true);
        jButton3.setEnabled(false);
        
        // clear text of 2nd text field
        jTextField13.setText("");
        
        
         //Winner
        
        //Variable declare
        String a= jTextField3.getText();
        String b= jTextField4.getText();
        String c= jTextField5.getText();
        String d= jTextField6.getText();
        String e= jTextField7.getText();
        String f= jTextField8.getText();
        String g= jTextField9.getText();
        String h= jTextField10.getText();
        String i= jTextField11.getText();
        
        
        //winner if commands
        if(a.equals(jTextField2.getText())&& e.equals(jTextField2.getText()) && i.equals(jTextField2.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 2 is the winner");
           
           player2=player2+1;
        }
        else if(a.equals(jTextField2.getText())&& b.equals(jTextField2.getText()) && c.equals(jTextField2.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 2 is the winner");
            player2=player2+1;
           
        }
        else if(a.equals(jTextField2.getText())&& d.equals(jTextField2.getText()) && g.equals(jTextField2.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 2 is the winner");
            player2=player2+1;
           
        }
        else if(g.equals(jTextField2.getText())&& h.equals(jTextField2.getText()) && i.equals(jTextField2.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 2 is the winner");
           
            player2=player2+1;
        }
        else if(c.equals(jTextField2.getText())&& f.equals(jTextField2.getText()) && i.equals(jTextField2.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 2 is the winner");
        player2=player2+1;
           
        }
        else if(c.equals(jTextField2.getText())&& e.equals(jTextField2.getText()) && g.equals(jTextField2.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 2 is the winner");
            player2=player2+1;
           
        }
          else if(b.equals(jTextField2.getText())&& e.equals(jTextField2.getText()) && h.equals(jTextField2.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 2 is the winner");
            player2=player2+1;
           
        }
          else if(d.equals(jTextField2.getText())&& e.equals(jTextField2.getText()) && f.equals(jTextField2.getText()))
        {
            JOptionPane.showMessageDialog(this,"Player 2 is the winner");
            player2=player2+1;
           
        }
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        
        //symbol can be changed
        jTextField1.setEditable(true);
        jTextField2.setEditable(true);
        
        // submit button unlocked
        jButton1.setEnabled(true);
        
        
        //clear lock and unlock
        jButton2.setEnabled(true);
        jButton3.setEnabled(false);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
              System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       this.setVisible(false);
       new Scorecard().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
